In [1]:
# Other Classification Exercise - KNN
# import everything
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sb

Peform the same exercise as Logistic Regression using KNN Classifier

In [2]:
from sklearn import datasets
# read in data from sample file
iris_data = pd.read_csv('iris-data-clean.csv')
# df.head() # show the first five rows
iris_data.tail()

NameError: name 'pd' is not defined

In [3]:
# make a copy of the dataframe
df_cat = df
# categorize by their weight
df_cat.loc[df['class']== "Sentosa", 'class'] = 0
df_cat.loc[df['class']== "Versicolor", 'class'] = 1
df_cat.loc[df['class'] == "Verginica", 'class'] = 2
df_cat

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class
0,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa
...,...,...,...,...,...
140,6.7,3.0,5.2,2.3,Virginica
141,6.3,2.5,5.0,1.9,Virginica
142,6.5,3.0,5.2,2.0,Virginica
143,6.2,3.4,5.4,2.3,Virginica
144,5.9,3.0,5.1,1.8,Virginica